{
    roomNumber: "BRI401",
    capacity: 3,
    availability: 3,
    floor:4,
    attachedBathroom: false,
    hostelName:"KAMBAN",
  },
  {
    roomNumber: "BRI402",
    capacity: 3,
    availability: 3,
    floor:4,
    attachedBathroom: false,
    hostelName:"KAMBAN",
  },
  {
    roomNumber: "BRI403",
    capacity: 3,
    availability: 3,
    floor:4,
    attachedBathroom: false,
    hostelName:"KAMBAN",
  },
  {
    roomNumber: "BRI404",
    capacity: 3,
    availability: 3,
    floor:4,
    attachedBathroom: false,
    hostelName:"KAMBAN",
  },
  {
    roomNumber: "BRI405",
    capacity: 3,
    availability: 3,
    floor:4,
    attachedBathroom: false,
    hostelName:"KAMBAN",
  },
  {
    roomNumber: "BRI406",
    capacity: 3,
    availability: 3,
    floor:4,
    attachedBathroom: false,
    hostelName:"KAMBAN",
  },
  {
    roomNumber: "BRI407",
    capacity: 3,
    availability: 3,
    floor:4,
    attachedBathroom: false,
    hostelName:"KAMBAN",
  },
  {
    roomNumber: "BRI408",
    capacity: 3,
    availability: 3,
    floor:4,
    attachedBathroom: false,
    hostelName:"KAMBAN",
  },
  {
    roomNumber: "BRI409",
    capacity: 3,
    availability: 3,
    floor:4,
    attachedBathroom: false,
    hostelName:"KAMBAN",
  },
  {
    roomNumber: "BRI410",
    capacity: 3,
    availability: 3,
    floor:4,
    attachedBathroom: false,
    hostelName:"KAMBAN",
  },