{
    roomNumber: "VLR401",
    capacity: 3,
    availability: 3,
    floor:4,
    attachedBathroom: false,
    hostelName:"VALLUVAR",
  },
  {
    roomNumber: "VLR402",
    capacity: 3,
    availability: 3,
    floor:4,
    attachedBathroom: false,
    hostelName:"VALLUVAR",
  },
  {
    roomNumber: "VLR403",
    capacity: 3,
    availability: 3,
    floor:4,
    attachedBathroom: false,
    hostelName:"VALLUVAR",
  },
  {
    roomNumber: "VLR404",
    capacity: 3,
    availability: 3,
    floor:4,
    attachedBathroom: false,
    hostelName:"VALLUVAR",
  },
  {
    roomNumber: "VLR405",
    capacity: 3,
    availability: 3,
    floor:4,
    attachedBathroom: false,
    hostelName:"VALLUVAR",
  },
  {
    roomNumber: "VLR406",
    capacity: 3,
    availability: 3,
    floor:4,
    attachedBathroom: false,
    hostelName:"VALLUVAR",
  },
  {
    roomNumber: "VLR407",
    capacity: 3,
    availability: 3,
    floor:4,
    attachedBathroom: false,
    hostelName:"VALLUVAR",
  },
  {
    roomNumber: "VLR408",
    capacity: 3,
    availability: 3,
    floor:4,
    attachedBathroom: false,
    hostelName:"VALLUVAR",
  },
  {
    roomNumber: "VLR409",
    capacity: 3,
    availability: 3,
    floor:4,
    attachedBathroom: false,
    hostelName:"VALLUVAR",
  },
  {
    roomNumber: "VLR410",
    capacity: 3,
    availability: 3,
    floor:4,
    attachedBathroom: false,
    hostelName:"VALLUVAR",
  },