/* eslint-disable */
console.log("haii");
const express = require("express");
const cors = require("cors");
const bodyParser = require("body-parser");
const morgan = require("morgan");
const { sequelize } = require("./models");
const cookieParser = require("cookie-parser");
// const sequel = require('./models');
const config = require("./config/config");
const app = express();
app.use(morgan("combined"));
app.use(bodyParser.json());
app.use(cors());
app.use(cookieParser());

require("./routes")(app);
const hostelRoomsData = [{
        roomNumber: "AMR001",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR002",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR003",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR004",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR005",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR006",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR007",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR008",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR009",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR010",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR101",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR102",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR103",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR104",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR105",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR106",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR107",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR108",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR109",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR110",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR201",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR202",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR203",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR204",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR205",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR206",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR207",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR208",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR209",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR210",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR301",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR302",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR303",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR304",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR305",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR306",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR307",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR308",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR309",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR310",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR401",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR402",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR403",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR404",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR405",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR406",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR407",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR408",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR409",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },
    {
        roomNumber: "AMR410",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: true,
        hostelName: "AMARAVATHI",
    },

    {
        roomNumber: "BHV001",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV002",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV003",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV004",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV005",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV006",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV007",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV008",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV009",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV010",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },

    {
        roomNumber: "BHV101",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV102",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV103",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV104",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV105",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV106",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV107",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV108",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV109",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV110",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV201",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV202",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV203",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV204",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV205",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV206",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV207",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV208",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV209",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV210",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV301",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV302",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV303",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV304",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV305",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV306",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV307",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV308",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV309",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV310",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV401",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV402",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV403",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV404",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV405",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV406",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV407",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV408",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV409",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "BHV410",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: true,
        hostelName: "BHAVANI",
    },
    {
        roomNumber: "KVR001",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR002",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR003",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR004",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR005",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR006",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR007",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR008",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR009",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR010",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR101",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR102",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR103",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR104",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR105",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR106",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR107",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR108",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR109",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR110",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR201",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR202",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR203",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR204",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR205",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR206",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR207",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR208",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR209",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR210",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR301",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR302",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR303",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR304",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR305",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR306",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR307",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR308",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR309",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR310",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR401",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR402",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR403",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR404",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR405",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR406",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR407",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR408",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR409",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "KVR410",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "KAVERI",
    },
    {
        roomNumber: "DRN001",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN002",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN003",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN004",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN005",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN006",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN007",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN008",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN009",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN010",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN101",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN102",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN103",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN104",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN105",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN106",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN107",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN108",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN109",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN110",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN201",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN202",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN203",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN204",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN205",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN206",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN207",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN208",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN209",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN210",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN301",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN302",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN303",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN304",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN305",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN306",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN307",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN308",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN309",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN310",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN401",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN402",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN403",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN404",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN405",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN406",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN407",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN408",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN409",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "DRN410",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "DHEERAN",
    },
    {
        roomNumber: "BRI001",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI002",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI003",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI004",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI005",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI006",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI007",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI008",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI009",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI010",
        capacity: 3,
        availability: 3,
        floor: 0,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI101",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI102",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI103",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI104",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI105",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI106",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI107",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI108",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI109",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI110",
        capacity: 3,
        availability: 3,
        floor: 1,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI201",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI202",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI203",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI204",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI205",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI206",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI207",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI208",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI209",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI210",
        capacity: 3,
        availability: 3,
        floor: 2,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI301",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI302",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI303",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI304",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI305",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI306",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI307",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI308",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI309",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI310",
        capacity: 3,
        availability: 3,
        floor: 3,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI401",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI402",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI403",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI404",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI405",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI406",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI407",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI408",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI409",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
    {
        roomNumber: "BRI410",
        capacity: 3,
        availability: 3,
        floor: 4,
        attachedBathroom: false,
        hostelName: "BHARATHI",
    },
];
const hostelInfoData = [{
        hostelName: "AMARAVATHI",
        floor: 5,
        rooms: 150,
        capacity: 4500,
        availability: 4500,
        facility: "Gym, Tv Room, Indoor Games, Computer Lab",
    },
    {
        hostelName: "BHAVANI",
        floor: 5,
        rooms: 150,
        capacity: 4500,
        availability: 4500,
        facility: " Tv Room, Indoor Games, Computer Lab",
    },
    {
        hostelName: "KAVERI",
        floor: 5,
        rooms: 150,
        capacity: 4500,
        availability: 4500,
        facility: " Tv Room, Indoor Games, Computer Lab,Beauty Parlour",
    },

    {
        hostelName: "DHEERAN",
        floor: 5,
        rooms: 150,
        capacity: 4500,
        availability: 4500,
        facility: " Tv Room, Indoor Games, Computer Lab,Gym",
    },
    {
        hostelName: "BHARATHI",
        floor: 5,
        rooms: 150,
        capacity: 4500,
        availability: 4500,
        facility: " Tv Room, Indoor Games, Computer Lab,Gym",
    },
    {
        hostelName: "KAMBAN",
        floor: 5,
        rooms: 150,
        capacity: 4500,
        availability: 4500,
        facility: " Tv Room, Indoor Games, Computer Lab",
    },
    {
        hostelName: "ELANGO",
        floor: 5,
        rooms: 150,
        capacity: 4500,
        availability: 4500,
        facility: " Tv Room, Indoor Games, Computer Lab,Gym",
    },
    {
        hostelName: "PONNAR",
        floor: 5,
        rooms: 150,
        capacity: 4500,
        availability: 4500,
        facility: " Tv Room, Indoor Games, Computer Lab",
    },
    {
        hostelName: "SANKAR",
        floor: 5,
        rooms: 150,
        capacity: 4500,
        availability: 4500,
        facility: " Tv Room, Indoor Games, Computer Lab,Gym",
    },
    {
        hostelName: "VALLUVAR",
        floor: 5,
        rooms: 150,
        capacity: 4500,
        availability: 4500,
        facility: " Tv Room, Indoor Games, Computer Lab,Gym",
    },
];
const hostelPermissionData = [{
        hostelName: "AMARAVATHI",
        booking: false,
        registration: false,
    },
    {
        hostelName: "BHARATHI",
        booking: false,
        registration: false,
    },
    {
        hostelName: "BHAVANI",
        booking: false,
        registration: false,
    },
    {
        hostelName: "KAVERI",
        booking: false,
        registration: false,
    },
    {
        hostelName: "DHEERAN",
        booking: false,
        registration: false,
    },
    {
        hostelName: "KAMBAN",
        booking: false,
        registration: false,
    },
    {
        hostelName: "ELANGO",
        booking: false,
        registration: false,
    },
    {
        hostelName: "PONNAR",
        booking: false,
        registration: false,
    },
    {
        hostelName: "SANKAR",
        booking: false,
        registration: false,
    },
    {
        hostelName: "VALLUVAR",
        booking: false,
        registration: false,
    },
];
const hostelForData = [{
        hostelName: "AMARAVATHI",
        gender: "FEMALE",
        year: 2,
    },
    {
        hostelName: "BHARATHI",
        gender: "MALE",
        year: 1,
    },
    {
        hostelName: "BHAVANI",
        gender: "FEMALE",
        year: 4,
    },
    {
        hostelName: "KAVERI",
        gender: "FEMALE",
        year: 1,
    },
    {
        hostelName: "KAVERI",
        gender: "FEMALE",
        year: 3,
    },
    {
        hostelName: "DHEERAN",
        gender: "MALE",
        year: 1,
    },
    {
        hostelName: "KAMBAN",
        gender: "MALE",
        year: 2,
    },
    {
        hostelName: "ELANGO",
        gender: "MALE",
        year: 2,
    },
    {
        hostelName: "PONNAR",
        gender: "MALE",
        year: 1,
    },
    {
        hostelName: "SANKAR",
        gender: "MALE",
        year: 4,
    },
    {
        hostelName: "VALLUVAR",
        gender: "MALE",
        year: 3,
    },
];
const permissionData = [{
        responsibility: "PRINCIPAL",
        bookingPermission: true,
        studentRegistration: true,
        changePermissions: true,
        level: 0
    },
    {
        responsibility: "ASSOCIATE WARDEN",
        bookingPermission: true,
        studentRegistration: true,
        changePermissions: true,
        level: 0
    }, {
        responsibility: "WARDEN",
        bookingPermission: true,
        studentRegistration: true,
        changePermissions: false,
        level: 1
    },
    {
        responsibility: "DEPUTY WARDEN",
        bookingPermission: false,
        studentRegistration: false,
        changePermissions: false,
        level: 2,
    }, {
        responsibility: "STAFF",
        bookingPermission: false,
        studentRegistration: false,
        changePermissions: false,
        level: 3,
    }
]
sequelize
    .sync()
    .then(() => {
        const { models } = sequelize;
        console.log(models);
        // models.hostelpermission.bulkCreate(hostelPermissionData);
        // models.hostelrooms.bulkCreate(hostelRoomsData);
        // models.hostelinfo.bulkCreate(hostelInfoData);
        // models.hostelfor.bulkCreate(hostelForData);
        // models.permission.bulkCreate(hostelForData);
    })
    .then(() => {
        app.listen(config.PORT || 3000);
        console.log(`server started on port ${config.PORT}`);
    })
    .catch((err) => {
        console.log(err);
    });
console.log(err);
});